name: realesrgan-x8_192x192
display_name: Real-ESRGAN-x8
task: super_resolution
reference: https://github.com/xinntao/Real-ESRGAN
description: 'Real-ESRGAN x8 super resolution. Fixed 192x192 RGB input. (Eval blocked: BSD100/bicubic_8x dataset not available.)'
macs: 818.75 GMACs
params: 16.73 M
inputs:
  - name: x
    shape: [1, 3, 192, 192]
    dtype: float32
    layout: NCHW
preprocessing:
  - type: resize
    mode: default
    width: 192
    height: 192
  - type: convertcolor
    form: BGR2RGB
  - type: div
    x: 255
  - type: transpose
    axis: [2, 0, 1]
  - type: expanddim
    axis: 0
postprocessing:
  - type: sr_postprocessing
    upscale_factor: 8
dataset:
  type: BSD100
  eval_path: ${DATA_ROOT}/BSD100/bicubic_8x
appendix:
  upscale_factor: 8
  hr_preprocessing:
    - type: convertcolor
      form: BGR2RGB
    - type: div
      x: 255
    - type: transpose
      axis: [2, 0, 1]
artifacts:
  path: ${MODEL_ROOT}/${MODEL_NAME}
profiles:
  onnx:
    target: onnx
    runtime:
      device: gpu
      batch_size: 1
  c-lite:
    target: dxnn
    compile:
      opt_level: 0
      quantization:
        lite:
          method: ema
          num_samples: 100
    runtime:
      buffer_count: 1
      device: 0
  q-lite:
    target: dxnn
    compile:
      quantization:
        lite:
          method: ema
          num_samples: 100
    runtime:
      buffer_count: 1
      device: 0
  q-pro:
    target: dxnn
    compile:
      quantization:
        pro:
          num_samples: 1024
          method: ema
    runtime:
      buffer_count: 1
      device: 0
